import Layout from '@/components/Layout'
import Head from 'next/head'
import React from 'react'

const FaQpage = () => {
    const arr = [1,2,3,4,5,6,7,8,9]
  return (
    <>
       <Head>
        <title>Paidley FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
        <div className='m-auto w-[80%] py-8'>
        <div className='horizontal space-y-5'>
        <h3 className='font-semibold text-3xl md:text-5xl '>Frequently Asked Questions</h3>
        <p className='gray-text max-w-2xl leading-12'>Everything you need to know about the product. Can&apos;t find the answer you&apos;re looking for? Please chat to our friendly team.</p>
        </div>

        <div className='py-8 grid gap-4 grid-cols-1  md:grid-cols-2 lg:grid-cols-3'>
        {arr.map((ar) => (
              <div key={ar} className='horizontal max-w-md space-y-3'>
              <h3 className='font-semibold text-[20px] normal-text'>How do I change my account  email?</h3>
              <p className='gray-text '>You can change the email address associated with your account by going to untitiled.com/account</p>
          </div>
        ))}

        </div>
       
        
        
        </div>

        <div className='m-auto w-[80%] md:w-[40%]  horizontal space-y-3'>
            <label htmlFor="faq">Have other questions?</label>
           <div className='relative'>
           <input type="text" className='bg-[#EAF0F6] w-full rounded-[12px] p-6' placeholder='search for questions' />
           <button className='btn absolute right-0 top-2'>Send</button> 
           </div>
        </div>

        

    </Layout>
    </>
  )
}

export default FaQpage