import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Nav from '@/components/landing-page-components/Nav'
import HeroBanner from '@/components/landing-page-components/HeroBanner'
import AccountsFeature from '@/components/landing-page-components/AccountsFeature'
import Setup from '@/components/landing-page-components/Setup'
import Faq from '@/components/landing-page-components/Faq'
import Footer from '@/components/landing-page-components/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Paidley</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
     <Nav />
     <HeroBanner />
     <AccountsFeature />
     <Setup />
     <Faq />
     <Footer />
      </main>
    </>
  )
}
